### ISSUE TITLE
link to install taichi (legacy branch) broken

### ISSUE THREAD

**Issue by themancalledjakob** [yuanming-hu/spgrid_topo_opt#11]
readme links to: `https://taichi.readthedocs.io/en/latest/installation.html#ubuntu-arch-linux-and-mac-os-x`
should be:  `https://taichi.readthedocs.io/en/stable/legacy_installation.html`

fixed in #10 

hope i do this right, thanks for your great work

**Comment by yuanming-hu** [comment]
Thanks for the PR and I believe it's working again now.
