### ISSUE TITLE
ti build is not a valid command

### ISSUE THREAD

**Issue by qingyuanhujnu** [yuanming-hu/spgrid_topo_opt#20]
I am new to Taichi, and when I follow the instructions, after I have successfully make the solver *.so, I type "ti build" and it reports "ti build is not a vaild command", anyone could help please?

**Comment by yuanming-hu** [comment]
You will need a legacy version of Taichi - see here: https://github.com/yuanming-hu/spgrid_topo_opt#installation-tested-on-ubuntu-16041804arch-linux-windowsos-x-not-supported.

**Comment by qingyuanhujnu** [comment]
Thank you Yuanming
