### ISSUE TITLE
visualize_density and max_iteration issue

### ISSUE THREAD

**Issue by nilparent** [yuanming-hu/spgrid_topo_opt#7]
I ran the wheel_ script with cg_iteration = 50, however the optimization kept going after 100 iterations so I stopped it manually. Do you have an idea on how to fix this?
Moreover the [ti vd fem file.tcb ] command is not recognized :
`Loading module topo_opt

              ☯ ☯ ☯ ☯ ☯ ☯ ☯ ☯              
 *******************************************
 **                Taichi                 **
 **                ~~~~~~                 **
 ** Open Source Computer Graphics Library **
 *******************************************
              ☰ ☱ ☲ ☳ ☴ ☵ ☶ ☷              

Running task [visualize_density]...
[E 07/31/20 10:27:16.521] [task.h:create@29] Implementation [task::visualize_density] not found!
[E 07/31/20 10:27:16.521] Received signal 6 (Aborted)`
I tried visualize_density instead of vd but it still didn't work.
And just a little question : is .tcb file convertible in .obj (after making it human readable?) or the solver does it automatially when it stops by its own (because my fem_obj is empty after running the optimization)?
Thank you very much for your help!

**Comment by senthurayyappan** [comment]
This is on ubuntu 18.04?

**Comment by nilparent** [comment]
Yes indeed I'm on Ubuntu 18.04Le 8 sept. 2020 18:54, Senthur Raj <notifications@github.com> a écrit :
This is on ubuntu 18.04?

**Comment by senthurayyappan** [comment]
Can you share the installation process?

EDIT: Installed it on ubuntu 18.04 (after failing to resolve few issues on 20.04), works! `ti run convert_fem_solve <>.tcb.zip --with-density` writes a .txt file with density values corresponding to each block. I was able to parse the file and apply a marching cubes algorithm to get the resulting mesh.

**Comment by nilparent** [comment]
thanks a lot!
