### ISSUE TITLE
FEM solve fails after a successful build.

### ISSUE THREAD

**Issue by senthurayyappan** [yuanming-hu/spgrid_topo_opt#8]
After installing ``taichi-legacy``, I got icc and mkl installed, I added the spgrid_topo_opt to ``projects`` and started building FEM solver. The build was successful and I performed ``ti build`` to finish the installation process. There were no errors during installation but when I execute example scripts from ``spgrid_topo_opt/scripts/``, I get **FEM solve has failed!**

![FEM solve](https://user-images.githubusercontent.com/25511437/92505049-1d70dd80-f221-11ea-9d4c-f6dcc7e57f68.png)

**Comment by jlxy11** [comment]
I have successfully install Taichi(legacy branch),icc and mkl in ubuntu18.04. but I'm new to Linux, so I don't know how to build the FEM solver.could you please tell me how to build FEM solver?@imsenthur
